# base image for container
FROM ubuntu:latest

# updates APT & upgrades currently installed software
RUN apt-get update
RUN apt-get upgrade -y

# echoes “Hello, World!” on terminal
CMD [ "echo", "Hello, World!" ]
